module.exports = {
    2: "Console",
    3: "FormattedConsoleOutput",
    4: "friend/FriendsUpdate",
    5: "friend/Message",
    6: "friend/ServerUpdate",
    7: "friend/BulkFriends",
    8: "Cosmetics",
    9: "friend/FriendRequest",
    16: "friend/FriendStatusUpdate",
    17: "friend/ClientFriendRemove",
    18: "friend/FriendUpdate",
    19: "ClientPlayerJoin",
    20: "ClientCosmetics",
    21: "friend/ClientFriendRequestUpdate",
    22: "friend/ClientRequestsStatus",
    23: "ClientCrashReport",
    35: "RequestProcessList",
    36: "ClientProcessList",
    40: "protocol/BlockedServer",
    41: "protocol/PinnedServer",
    43: "protocol/GrantStaffMod",
    69: "protocol/RankProfile"
}